# site configuration

theme: jekyll-theme-chirpy

lang: en

# https://kevinnovak.github.io/Time-Zone-Picker
timezone: America/New_York

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md

# main title
title: John's Quizzo
